server:
  port: 8080

spring:
  datasource:
    username: root
    password: skillbox
    url:
      jdbc:mysql://localhost:3306/search_engine?
      useSSL=false&
      requireSSL=false&
      allowPublicKeyRetrieval=true&
      createDatabaseIfNotExist=true
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
    enabled: true
    drop-first: false

logging:
  file:
    name: logs/SearchEngine.log
#  level:
#    root: "warn"
#    org.springframework.web: "warn"
#    org.hibernate: "warn"
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} %level - %msg%n"
#    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %level %logger - %msg%n"


# example values

indexing-settings:
  exclude-url-parameters: true # default value: true
  path-max-length: 767 # length of path without main url. MAX allowed value is 767. Default value: 767
  user-agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0 # default value: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:129.0) Gecko/20100101 Firefox/129.0
  referrer: https://www.yandex.ru/ # default value: https://www.yandex.ru/
  request-timeout: 500 # default value: 500
  check-visited-pages-algorithm: 0 # 0 - check with crating additional Set (advanced performance), 1 - check with request to DB (requires less RAM), other values are equals 1. Default value: 0
  sites:
    - url: http://affix.ru
      name: Affix
    - url: https://sendel.ru/
      name: Sendel.ru
    - url: https://www.fc-baltika.ru
      name: Baltika Kaliningrad
    - url: https://www.fc-baltika.ru/
      name: BALTIKA
    - url: https://www.FC-baltika.su
      name: Baltika.su
#    - url: http://www.SKILLBOX.ru
#      name: Skillbox
#    - url: https://www.Skillbox.ru
#      name: Skillbox
#    - url: https://www.playback.ru
#      name: PlayBack.Ru
#    - url: https://www.lenta.ru
#      name: Лента.ру
#    - url: https://www.coxo.ru/
#      name: Coxo
#    - url: https://www.baltmaximus.com/
#      name: Baltmaximus
#    - url: http://www.balticstyle.ru/
#      name: Baltik Style
#    - url: https://www.splav.ru
#      name: Splav.ru
#    - url: https://klgtu.ru/
#      name: KGTU